### PR TITLE
autodetect correct kded touchpad module

### LINKED ISSUE #9: [BUG] [CRITICAL] Touchpad is not working after sleep mode on Arch Linux Plasma Desktop.
I installed tuxedo-touchpad-switch via aur. I am using KDE Plasma version 5.24. When I wake the device from sleep mode, the touchpad light turns on, but I cannot activate the touchpad. Although the touchpad appears to be enabled in KDE, the touchpad does not work. I didn't get any log, but if you tell me how to get log, I can send log.

### PR DESCRIPTION
**Pull request by brainpower**
plasma 5.24 renamed the "touchpad" kded module to "kded_touchpad".
fix this by listing all loaded modules in kded and look for the correct
module name to use.

Otherwise it would try to use the wrong one, fail to initialize,
and not re-enable the touchpad after resuming after suspend
leaving the user with an unusable touchpad and no easy way to enable it.

This now also gives an error message and exits, if no touchpad module is
loaded.

Fixes: #9

---

I tried to follow the overall coding style, hope I didn't miss anything.

### CODE REVIEW

**Comment by Matombo** [comment]
Seems good. Thanks for your contribution.

I will test it later.

Small addition (already fixed in my dev branch): g_variant_iter_loop does need free when break is used (it does not need free when break is not used, as g_variant_iter_loop frees the previous element automatically and ends with a null pointer): https://developer-old.gnome.org/glib/stable/glib-GVariant.html#g-variant-iter-loop

**Comment by brainpower** [comment]
hm, i read that when using `g_variant_iter_loop`, freeing is needed for all things for which the equivalent `g_variant_get()` return value would have to be freed...
> If you break out of a such a while loop using g_variant_iter_loop() then you must free or unreference all the unpacked values as you would with g_variant_get(). Failure to do so will cause a memory leak.
https://docs.gtk.org/glib/method.VariantIter.loop.html

`get_string` documents, that strings don't need to be freed, because the gvariant stays the owner of it...
That's at least how I read this: https://docs.gtk.org/glib/method.Variant.get_string.html

that's why I thought, free would not be needed, and `valgrind` did not show an isssue....

I'm no glib expert though, so take my take on this with a grain of salt :)

**Comment by Matombo** [comment]
> I'm no glib expert though, so take my take on this with a grain of salt :)

Me neither XD. All I go by is the documentation.

For get_string it's explicitly stated that the return value is still owned by the instance, while for the _loop function the value is "unpacked" into the argument.

Valgrind only has some "possible lost" bytes when closing with sigterm/ctrl+c which is currently the only way to close. Same for your variant?

Other than this the new version works as intended, pushing now. The prebuilt new version will propably land in the package repos on monday.

**Comment by brainpower** [comment]
> Valgrind only has some "possible lost" bytes when closing with sigterm/ctrl+c which is currently the only way to close. Same for your variant?

yes, iirc. If it had reported anything more, I would have "fixed" it before submitting. (I had inserted a `exit(0);` after my changes to test, though ... )

Well anyway, if it does not complain about possibly double-freeing stuff, your version should be more robust, no matter which interpretation is correct. :D

**Pull request merged**
